const db = require('./db');
const { v4: uuidv4 } = require('uuid');

const createTodo = (content, ownerId) => {
    // id will be auto-generated by SQLite
    const now = Date.now();
    const stmt = db.prepare('INSERT INTO todos (content, owner_id, is_completed, created_at) VALUES (?, ?, 0, ?)');
    const info = stmt.run(content, ownerId, now);
    return info.lastInsertRowid; // Return the new integer ID
};

const getTodos = () => {
    const stmt = db.prepare('SELECT * FROM todos ORDER BY created_at DESC');
    return stmt.all();
};

const getTodoById = (id) => {
    const stmt = db.prepare('SELECT * FROM todos WHERE id = ?');
    return stmt.get(id);
};

const toggleTodo = (id) => {
    const todo = getTodoById(id);
    if (todo) {
        const newStatus = todo.is_completed ? 0 : 1;
        const stmt = db.prepare('UPDATE todos SET is_completed = ? WHERE id = ?');
        stmt.run(newStatus, id);
    }
};

const deleteTodo = (id) => {
    const stmt = db.prepare('DELETE FROM todos WHERE id = ?');
    stmt.run(id);
};

module.exports = {
    createTodo,
    getTodos,
    getTodoById,
    toggleTodo,
    deleteTodo
};
